name: Package Application with Pyinstaller and release

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Package Windows Application
      uses: JackMcKew/pyinstaller-action-windows@main
      with:
        path: ./

    - name: Package Linux Application
      uses: JackMcKew/pyinstaller-action-linux@main
      with:
        path: ./

    - name: package to zip files
      run: |
        cp config.ini.example dist/windows
        cp config.ini.example dist/linux
        zip -r dist/Windows.zip dist/windows
        zip -r dist/Linux.zip dist/linux

    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          dist/Windows.zip
          dist/Linux.zip